export enum State {
    "Alaska",
    "California",
    "Arizona",
    "Colorado",
    "Iowa",
    "Oregon",
    "Washington",
    "Indiana",
    "Kansas",
    "Missouri",
    "Nebraska",
    "New Mexico",
    "Nevada",
    "Oklahoma",
    "Tennessee",
    "Utah",
    "West Virginia",
    "Idaho",
    "Montana",
    "North Dakota",
    "South Dakota",
    "Vermont",
    "Wyoming",
    "Puerto Rico",
    "U.S. Virgin Islands",
    "Texas",
    "Alabama",
    "Georgia",
    "Florida",
    "Louisiana",
    "Mississippi",
    "South Carolina",
    "Connecticut",
    "District of Columbia",
    "Delaware",
    "Kentucky",
    "Massachusetts",
    "Maryland",
    "North Carolina",
    "New Jersey",
    "New York",
    "Ohio",
    "Pennsylvania",
    "Rhode Island",
    "Virginia",
    "Wisconsin",
    "Michigan",
    "Hawaii",
    "Maine",
    "Minnesota",
    "New Hampshire",
    "Illinois",
    "Arkansas",
}